<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="13" total="17" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Login Test Suite" duration-ms="112" started-at="2020-11-26T00:58:07 EET" finished-at="2020-11-26T00:58:08 EET">
    <groups>
      <group name="regression">
        <method signature="TaskTestNG.sayHaveAGoodDay()[pri:0, instance:com.syntax.class01.TaskTestNG@4b1c1ea0]" name="sayHaveAGoodDay" class="com.syntax.class01.TaskTestNG"/>
        <method signature="TaskWithAnnotations.test2()[pri:0, instance:com.syntax.class01.TaskWithAnnotations@4d41cee]" name="test2" class="com.syntax.class01.TaskWithAnnotations"/>
        <method signature="TestCasesHRMS.validLogin()[pri:0, instance:com.syntax.class01.TestCasesHRMS@17579e0f]" name="validLogin" class="com.syntax.class01.TestCasesHRMS"/>
        <method signature="TestNGDependencies.login()[pri:0, instance:com.syntax.class01.TestNGDependencies@3712b94]" name="login" class="com.syntax.class01.TestNGDependencies"/>
      </group> <!-- regression -->
    </groups>
    <test name="Login Test" duration-ms="112" started-at="2020-11-26T00:58:07 EET" finished-at="2020-11-26T00:58:08 EET">
      <class name="com.syntax.class01.TaskWithAnnotations">
        <test-method status="PASS" signature="test2()[pri:0, instance:com.syntax.class01.TaskWithAnnotations@4d41cee]" name="test2" duration-ms="3" started-at="2020-11-26T00:58:08 EET" finished-at="2020-11-26T00:58:08 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.syntax.class01.TaskWithAnnotations -->
      <class name="com.syntax.class01.TestCasesHRMS">
        <test-method status="FAIL" signature="validLogin()[pri:0, instance:com.syntax.class01.TestCasesHRMS@17579e0f]" name="validLogin" duration-ms="9" started-at="2020-11-26T00:58:08 EET" finished-at="2020-11-26T00:58:08 EET">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.syntax.class01.TestCasesHRMS.validLogin(TestCasesHRMS.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
      </class> <!-- com.syntax.class01.TestCasesHRMS -->
      <class name="com.syntax.class01.TestNGDependencies">
        <test-method status="PASS" signature="login()[pri:0, instance:com.syntax.class01.TestNGDependencies@3712b94]" name="login" duration-ms="2" started-at="2020-11-26T00:58:08 EET" finished-at="2020-11-26T00:58:08 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- com.syntax.class01.TestNGDependencies -->
      <class name="com.syntax.class01.TaskTestNG">
        <test-method status="PASS" signature="sayHaveAGoodDay()[pri:0, instance:com.syntax.class01.TaskTestNG@4b1c1ea0]" name="sayHaveAGoodDay" duration-ms="19" started-at="2020-11-26T00:58:08 EET" finished-at="2020-11-26T00:58:08 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sayHaveAGoodDay -->
      </class> <!-- com.syntax.class01.TaskTestNG -->
    </test> <!-- Login Test -->
  </suite> <!-- Login Test Suite -->
</testng-results>
